version: 2.1
jobs:
  "build":
    docker:
      - auth:
          password: $DOCKER_PASS
          username: $DOCKER_USER
        image: circleci/rust:1.53
    working_directory: ~/fdk-rust
    steps:
      - checkout
      - run:
          command: |
            cargo build
  "test":
    docker:
      - auth:
          password: $DOCKER_PASS
          username: $DOCKER_USER
        image: circleci/rust:1.53
    working_directory: ~/fdk-rust
    steps:
      - checkout
      - run:
          command: |
            cargo test
  "deploy":
    docker:
      - auth:
          password: $DOCKER_PASS
          username: $DOCKER_USER
        image: circleci/rust:1.53
    working_directory: ~/fdk-rust
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          command: |
            cargo build
      - deploy:
          command: |
            if [[ "${CIRCLE_BRANCH}" == "master" && -z "${CIRCLE_PR_REPONAME}" ]]; then
              printenv DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
              git config --global user.email "ci@fnproject.com"
              git config --global user.name "CI"
              git branch --set-upstream-to=origin/${CIRCLE_BRANCH} ${CIRCLE_BRANCH}

              cargo login ${FN_CARGO_TOKEN}

              ./release.sh
              ./build_image.sh 1.53
              ./release_images.sh
            fi

workflows:
  version: 2
  commit:
    jobs:
      - "build"
      - "test"
      - "deploy"
